spring.application.name=Employee-Management

spring.datasource.url=jdbc:postgresql://${postgres.railway.internal}:${5432}/${railway}
spring.datasource.username=${postgres}
spring.datasource.password=${iSZTJMZuxvsckFknzBlkqqnZLWskxaRg}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.springframework.security=DEBUG